// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAPiQgQfpNmQa8rtJokNFP-JysSiv0BCc',
    appId: '1:582095117064:web:ccaa1ad7979403829beabd',
    messagingSenderId: '582095117064',
    projectId: 'edu-ai-7c33a',
    authDomain: 'edu-ai-7c33a.firebaseapp.com',
    storageBucket: 'edu-ai-7c33a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCefIvUngl9AxOflqOvtJCd5H4nur44H2U',
    appId: '1:582095117064:android:4672ed1eb85b4ec59beabd',
    messagingSenderId: '582095117064',
    projectId: 'edu-ai-7c33a',
    storageBucket: 'edu-ai-7c33a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCthPEFM3d7L2gWshR4mIoIYUoFHrJUNU0',
    appId: '1:582095117064:ios:1b69de20d72bf7d79beabd',
    messagingSenderId: '582095117064',
    projectId: 'edu-ai-7c33a',
    storageBucket: 'edu-ai-7c33a.appspot.com',
    iosBundleId: 'com.example.eduAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCthPEFM3d7L2gWshR4mIoIYUoFHrJUNU0',
    appId: '1:582095117064:ios:1b69de20d72bf7d79beabd',
    messagingSenderId: '582095117064',
    projectId: 'edu-ai-7c33a',
    storageBucket: 'edu-ai-7c33a.appspot.com',
    iosBundleId: 'com.example.eduAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAPiQgQfpNmQa8rtJokNFP-JysSiv0BCc',
    appId: '1:582095117064:web:2d2826e4e3c39fa19beabd',
    messagingSenderId: '582095117064',
    projectId: 'edu-ai-7c33a',
    authDomain: 'edu-ai-7c33a.firebaseapp.com',
    storageBucket: 'edu-ai-7c33a.appspot.com',
  );

}